# Generated by Django 3.1.7 on 2021-05-05 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210505_2031'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Blog',
        ),
        migrations.RenameModel(
            old_name='LatestNews',
            new_name='LatestBlog',
        ),
    ]
